import { StyleSheet } from "react-native";
import { AppColors } from "../../constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  bgShape: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.35,
  },
  bgShape1: {
    width: 320,
    height: 320,
    backgroundColor: "#764ba2",
    top: -80,
    right: -80,
  },
  bgShape2: {
    width: 250,
    height: 250,
    backgroundColor: "#f5576c",
    bottom: -60,
    left: -60,
  },
  card: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "rgba(22, 23, 34, 0.96)",
    borderRadius: 24,
    padding: 28,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 0.5,
    shadowRadius: 25,
    elevation: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 24,
    alignSelf: "flex-start",
  },
  backText: {
    color: "#9ca3af",
    fontSize: 14,
    marginLeft: 6,
  },
  iconContainer: {
    width: 64,
    height: 64,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: "#fff",
    textAlign: "center",
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 13,
    color: "#9ca3af",
    textAlign: "center",
    marginBottom: 24,
    fontWeight: "300",
    lineHeight: 18,
  },
  inputBox: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    height: 48,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 12,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  inputError: {
    borderColor: AppColors.error,
  },
  textInput: {
    flex: 1,
    color: "#fff",
    fontSize: 14,
    height: "100%",
  },
  inputIcon: {
    marginLeft: 10,
  },
  eyeIconBtn: {
    padding: 6,
  },
  errorMsgText: {
    color: AppColors.error,
    fontSize: 11,
    marginTop: -8,
    marginBottom: 10,
    paddingLeft: 4,
  },
  generalError: {
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.3)",
  },
  generalErrorText: {
    color: "#ef4444",
    fontSize: 13,
    fontWeight: "600",
    textAlign: "center",
  },
  // Password requirements
  requirementsContainer: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  requirementsTitle: {
    fontSize: 12,
    color: "#9ca3af",
    fontWeight: "600",
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  requirementRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  requirementText: {
    fontSize: 12,
    marginLeft: 8,
  },
  requirementMet: {
    color: "#34c759",
  },
  requirementNotMet: {
    color: "#6b7280",
  },
  submitBtn: {
    width: "100%",
    height: 48,
    borderRadius: 12,
    overflow: "hidden",
    marginTop: 8,
  },
  btnGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  btnContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  submitBtnText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },
  // Success
  successContainer: {
    alignItems: "center",
    paddingVertical: 10,
  },
  successIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(52, 199, 89, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    borderWidth: 2,
    borderColor: "rgba(52, 199, 89, 0.3)",
  },
  successTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#fff",
    marginBottom: 8,
  },
  successSubtitle: {
    fontSize: 13,
    color: "#9ca3af",
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 18,
  },
  loginBtn: {
    width: "100%",
    height: 48,
    borderRadius: 12,
    overflow: "hidden",
  },
  loginBtnGradient: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  loginBtnText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },
});
