import { StyleSheet } from "react-native";
import { AppColors } from "../../constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  bgShape: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.35,
  },
  bgShape1: {
    width: 320,
    height: 320,
    backgroundColor: "#764ba2",
    top: -80,
    left: -80,
  },
  bgShape2: {
    width: 250,
    height: 250,
    backgroundColor: "#f5576c",
    bottom: -60,
    right: -60,
  },
  card: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "rgba(22, 23, 34, 0.96)",
    borderRadius: 24,
    padding: 28,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 0.5,
    shadowRadius: 25,
    elevation: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 24,
    alignSelf: "flex-start",
  },
  backText: {
    color: "#9ca3af",
    fontSize: 14,
    marginLeft: 6,
  },
  iconContainer: {
    width: 64,
    height: 64,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: "#fff",
    textAlign: "center",
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 13,
    color: "#9ca3af",
    textAlign: "center",
    marginBottom: 24,
    fontWeight: "300",
    lineHeight: 18,
  },
  generalErrorText: {
    color: "#ef4444",
    fontSize: 13,
    fontWeight: "600",
    textAlign: "center",
  },
  submitBtn: {
    width: "100%",
    height: 48,
    borderRadius: 12,
    overflow: "hidden",
    marginTop: 8,
  },
  btnGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  // Verification success
  successContainer: {
    alignItems: "center",
    paddingVertical: 10,
  },
  successIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(52, 199, 89, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    borderWidth: 2,
    borderColor: "rgba(52, 199, 89, 0.3)",
  },
  successTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#fff",
    marginBottom: 8,
  },
  successSubtitle: {
    fontSize: 13,
    color: "#9ca3af",
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 18,
  },
  resetLinkBtn: {
    width: "100%",
    height: 48,
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 12,
  },
  resetLinkGradient: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  resetLinkText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },
  backToLoginBtn: {
    paddingVertical: 12,
  },
  backToLoginText: {
    color: "#9ca3af",
    fontSize: 13,
    textAlign: "center",
  },
  backToLoginLink: {
    color: AppColors.primary,
    fontWeight: "600",
  },
});
